# Generated by Django 5.0.6 on 2024-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('job_title', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
